### ISSUE TITLE
Update the HW interface and KRL scripts to:

### ISSUE THREAD

**Issue by carlosjoserg** [CentroEPiaggio/kuka-lwr#4]
The joint impedance control strategy allow to specify position and effort, so why not to:
- [x] Include a position_controller interface for joints, that allow to use a joint position controller
- [ ] The same as above, but to have a hybrid setpoint: position and effort, which again will still use the joint impedance control kuka strategy (this might require hacking ros_control, not urgent for now)
Besides, it would be advisable to:
- [x] Add the posibility to change from Monitor/Control mode, and to go for Gravity Compensation (the latter is useful for hand-eye calibration, safety triggered behavior, etc.)
- [x] Allow the change of joint stiffness on-line, perhaps create a stiffness controller to track stiffness trajectories (@manuelbonilla for your thesis?)

**Comment by carlosjoserg** [comment]
Just pinging the issue. 

The last item is implemented in the `multi-robot-test` branch, and it is really cool to see how the arm become stiffer gradually according to the speed scaling !

Cheers.

**Comment by marcoesposito1988** [comment]
There is some valuable information regarding it [here](https://toychest.ai.uni-bremen.de/wiki/projects:kuka_lwr). There is also the [KRL script](https://toychest.ai.uni-bremen.de/wiki/lib/exe/fetch.php?tok=e66198&media=https%3A%2F%2Ftum-ros-pkg.svn.sourceforge.net%2Fsvnroot%2Ftum-ros-pkg%2Fdrivers%2Fkuka_fri%2Fscripts%2Ffri_hand.src) they use, along with the ["background submit interpreter"](https://toychest.ai.uni-bremen.de/wiki/lib/exe/fetch.php?tok=540892&media=https%3A%2F%2Ftum-ros-pkg.svn.sourceforge.net%2Fsvnroot%2Ftum-ros-pkg%2Fdrivers%2Fkuka_fri%2Fscripts%2Fsps.sub).

It seems to include switching between monitor and control mode, and it should be robust to the (dangerous) problem they talk about in the page at the "FRI and KRL Movements" section.
