### ISSUE TITLE
Effort controllers failing when using PID class

### ISSUE THREAD

**Issue by manuelbonilla** [CentroEPiaggio/kuka-lwr#55]
Hi Guys,
I'm trying to use the one_task_inverse_dynamics_JL controller.
It was crashing always when updating. I saw that it is because it is using KinematicChainControllerBase instead of PIDKinematicChainControllerBase.
I suppose it is the same for all controllers generating torque commands or at least the ones using PID interfaces.
am I wrong?

**Comment by carlosjoserg** [comment]
Could be, after several HWiface updates, I haven't test how all controllers behave, only a couple of them.

Did you catch the line in which it is crashing?
Are you trying in simulation or in the real robot?

**Comment by carlosjoserg** [comment]
I believe this was solved with 07c297b6c5c371d8f048f9ce440ca4c47f33c722
