### ISSUE TITLE
What are the high frequency command capacities of the package ?

### ISSUE THREAD

**Issue by nstaub** [CentroEPiaggio/kuka-lwr#64]
I have to use a kuka-lwr 4+ for a project and would like to command it through ROS.
I would like to use the package kuka-lwr that you developed, but before  could you provide me the following detail is it possible to do joint impedance control or pure joint torque control at 1kHz, if not what are the performance achievable with classical ubuntu setup or is there any alternative out there ?

Thanks in advance,
Nicolas

**Comment by carlosjoserg** [comment]
Hi @nstaub,

Right now, I don't think you can. So far, I've tested the joint impedance strategy only sending position and stiffness @500Hz (2ms) top.

Back in old times, we managed to do joint position / Cartesian impedance strategy @1Khz with @manuelbonilla using the Stanford FRI libraries on regular Ubuntu.

On the other hand, the IOC group at Barcelona lead by @lepalom, has CMake'd (among other small useful mods) those libraries [here](https://github.com/iocroblab/fril), which are already linked in this project, see [here](https://github.com/CentroEPiaggio/kuka-lwr/blob/master/lwr_hw/CMakeLists.txt#L87-L97). They can do torque control @1KHz under xenomai

Thus, we are working on testing that interface behind the ros-control layer to see if we can have the RT option within the package.
