### ISSUE TITLE
Missing moveit_planning_execution.launch

### ISSUE THREAD

**Issue by marcoesposito1988** [CentroEPiaggio/kuka-lwr#83]
The file was added in cee59d494bf7afe5eda331fbf9cae00a4b4b792f, but I can't find it any more in master.

Was it devoured by some git merge?

**Comment by carlosjoserg** [comment]
Hi @marcoesposito1988 Yep, I see it was out in #18, but I don't think on purpose, too many changes in that PR, feel free to add it again, and my apologies !

**Comment by marcoesposito1988** [comment]
I thought so :rofl: no problem, I will make a pull request to put it back

**Comment by marcoesposito1988** [comment]
BTW: in the current RViz configuration, the planning request marker size is set to zero. This means, that you can't see the marker to command the robot. This can be EXTREMELY confusing for a newbie just trying out the package (I think I spent half an hour figuring this out myself, including recompiling RViz!)

Would you mind if I add another RViz config file to be loaded by moveit_planning_execution.launch? This way your setup would not change, but new users would be not as confused.

**Comment by marcoesposito1988** [comment]
Fixed by #88
