### ISSUE TITLE
Folder re-organization, again.

### ISSUE THREAD

**Issue by carlosjoserg** [CentroEPiaggio/kuka-lwr#9]
Hi all,

This issue is just to inform you that in the next commit there will be the following changes, which I believe are beneficial:

* All folders are gonna be moved two levels up to have a cleaner tree structure, and one README file explaining how to use the package.
* Get rid of the FRI-Stanford library, we don't use it in this package and there is already a place to download: http://cs.stanford.edu/people/tkr/fri/html/

So, I will wait for a while just in case you have any suggestion/objection, and after that, I'd kindly ask you to update/sync your local repos.

**Comment by enricocorvaglia** [comment]
It's fine to me, of course.
